### ISSUE TITLE
Naming consistency in worldcereal use case

### ISSUE THREAD

**Issue by soxofaan** [ESA-APEx/apex_algorithms#10]
Initial use case is based on worldcereal, but there is a bit of inconsistency naming-wise:

algorithm_catalog/**worldcereal**.json has id **worldcereal_maize**
https://github.com/ESA-APEx/apex_algorithms/blob/99a92be5fcd44435e20586379a09c59e45a833a3/algorithm_catalog/worldcereal.json#L2

it also links to openeo_udp/**worldcereal_inference**.json which has id **worldcereal_croptype**
https://github.com/ESA-APEx/apex_algorithms/blob/99a92be5fcd44435e20586379a09c59e45a833a3/openeo_udp/worldcereal_inference.json#L23

Moreover, algorithm_invocations/**worldcereal**.json has id **maize_2020_belgium**
https://github.com/ESA-APEx/apex_algorithms/blob/99a92be5fcd44435e20586379a09c59e45a833a3/algorithm_invocations/worldcereal.json#L3

Are all these different names intended?

I think it would help to keep things manageable to at least keep file name and id inside the file in sync. I could set up pre-commit hooks to enforce this.

Moreover, as there is a 1-to-1 relation (I think) between algorithm_catalog and openeo_udp entries, I would synchronize names there too

**Comment by jdries** [comment]
Nothing of this is really intendended or set in stone.
Lets indeed align id with filename. The actual choice may not yet matter at the moment, because the worldcereal example is anyway going to change further.

**Comment by soxofaan** [comment]
fixed now (with unit test coverage to avoid adding inconsistent use cases in the future)
