### ISSUE TITLE
"specification" wrapper in UDP json

### ISSUE THREAD

**Issue by soxofaan** [ESA-APEx/apex_algorithms#11]
https://github.com/ESA-APEx/apex_algorithms/blob/99a92be5fcd44435e20586379a09c59e45a833a3/openeo_udp/worldcereal_inference.json#L1-L23

is this top-level "specification" wrapper intended? Our current UDP-from-URL machinery expects the UDP without that

**Comment by jdries** [comment]
my bad, not sure where that came from.
