### ISSUE TITLE
start apex-python-tools repo

### ISSUE THREAD

**Issue by jdries** [ESA-APEx/apex_algorithms#3]
bootstrap new open source python project in this github org.

Minimal functionality to start with:
- a data class for an [APEx algorithm]( https://github.com/ESA-APEx/apex_algorithms/blob/main/algorithm_catalog/worldcereal.json)
- an 'algorithm repo' class that allows to fetch the algorithms (from the repo, can even be hardcoded)

General design docs: https://jdries-vito.quarto.pub/apex-design/algorithm_hosting.html

**Comment by soxofaan** [comment]
package name (e.g. for users to import in their code)?

- esa_apex
- apexeo
- esa_plaza
- esa_application_hub
- esa_app_hub

**Comment by soxofaan** [comment]
Created repo at https://github.com/ESA-APEx/esa-apex-toolbox-python with a package that users can import with `import esa_apex_toolbox`
Note I went very generic with this naming just to have something to work from. Naming should probably be finetuned later, after feedback of ESA for example

**Comment by soxofaan** [comment]
- [x] initial data class for an APEx algorithm
- [x]  initial 'algorithm repo' class that allows to fetch the algorithms (from the repo, can even be hardcoded)

**Comment by soxofaan** [comment]
to summarize the naming issue, current situation:
- `esa-apex-toolbox-python` repo name
- `esa-apex-toolbox` to `pip install`
- `esa_apex_toolbox` to `import`

**Comment by soxofaan** [comment]
feedback to finetune naming will be received later this week

**Comment by soxofaan** [comment]
I think we can close this ticket for now (especially given next step https://github.com/ESA-APEx/apex_algorithms/issues/15)
