### ISSUE TITLE
record algorithm output area in scenario metrics

### ISSUE THREAD

**Issue by jdries** [ESA-APEx/apex_algorithms#38]
output area allows us to compute cost per output area
perhaps it's best to have 2 metrics:
output pixels, in megapixel
output resolution, in m²

Then we can avoid that low resolution algorithms have a seemingly low cost per km², but we can still compute it if we want to?

**Comment by soxofaan** [comment]
added these two new metrics:
```
[
        "results:proj:shape:area:megapixel",
        0.033369
      ],
      [
        "results:proj:bbox:area:utm:km2",
        3.3369
      ]
```

**Comment by soxofaan** [comment]
closing this one for now: new metrics have been added, and are being picked up by dashboard
