### ISSUE TITLE
Set up initial benchmark for worldcereal

### ISSUE THREAD

**Issue by JeroenVerstraelen** [ESA-APEx/apex_algorithms#4]
A simple initial benchmark workflow using the worldcereal scenario.
No regression test, no metrics

Github action, doesn't have to be recurrent yet.

**Comment by soxofaan** [comment]
initial setup is done

- added package with reusable test/benchmark utilities
- added initial unit tests (also triggered from github actions)
- added initial benchmark 
    - githbub workflow just runs one benchmark at random now
    - benchmark still fails because there is no auth setup yet

**Comment by soxofaan** [comment]
First benchmark batch job is now running, fully triggered from GitHub workflow:

`j-24062104655b4a8d91b124f13a3b625f` from workflow https://github.com/ESA-APEx/apex_algorithms/actions/runs/9616807287

**Comment by soxofaan** [comment]
So the basics are in place now.

Quite some further finetuning and documentation to be covered (see `TODO` comments in the code)

**Comment by soxofaan** [comment]
because the worldcereal use case is still failing, I now added a very simple max NDVI UDP and benchmark scenario which now successfully runs in the benchmark workflow

**Comment by soxofaan** [comment]
Initial benchmark setup, with a daily run can be checked at https://github.com/ESA-APEx/apex_algorithms/actions/workflows/benchmarks.yaml

note that it sometimes works, and sometimes fails, but that is indication that the benchmark system works: one benchmark scenario (max_ndvi) finishes, while the worldcereal one does not work yet

**Comment by soxofaan** [comment]
I think it's time to close this one: basics are in place, 
and follow-up tickets are created, e.g.:
- #5 
- #7 
- #14
- #15 
- #16 
- #17
