### ISSUE TITLE
failing benchmark "eurac_pv_farm_detection"

### ISSUE THREAD

**Issue by soxofaan** [ESA-APEx/apex_algorithms#53]
last failed run at the time: https://github.com/ESA-APEx/apex_algorithms/actions/runs/11651518487/job/32441579065

benchmark failure due to job failure

```
0:03:51 Job 'cdse-j-241103a6da9446b8bd1c45ef9b907fae': running (progress N/A)
0:04:50 Job 'cdse-j-241103a6da9446b8bd1c45ef9b907fae': running (progress N/A)
0:05:50 Job 'cdse-j-241103a6da9446b8bd1c45ef9b907fae': error (progress N/A)
Your batch job 'cdse-j-241103a6da9446b8bd1c45ef9b907fae' failed. Error logs:
```
> [{'id': '[1730638938643, 96700]', 'time': '2024-11-03T13:02:18.643Z', 'level': 'error', 'message': 'Task 0 in stage 57.0 failed 4 times; aborting job'}, {'id': '[1730638938651, 287487]', 'time': '2024-11-03T13:02:18.651Z', 'level': 'error', 'message': 'Stage error: Job aborted due to stage failure: Task 0 in stage 57.0 failed 4 times, most recent failure: Lost task 0.3 in stage 57.0 (TID 2820) (10.42.187.136 executor 6): org.apache.spark.api.python.PythonException: Traceback (most recent call last):\n  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 830, in main\n    process()\n  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 822, in process\n    serializer.dump_stream(out_iter, outfile)\n  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 146, in dump_stream\n    for obj in iterator:\n  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/util.py", line 81, in wrapper\n    return f(*args, **kwargs)\n  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 57, in memory_logging_wrapper\n    return function(*args, **kwargs)\n  File "/opt/openeo/lib/python3.8/site-packages/epsel.py", line 44, in wrapper\n    return _FUNCTION_POINTERS[key](*args, **kwargs)\n  File "/opt/openeo/lib/python3.8/site-packages/epsel.py", line 37, in first_time\n    return f(*args, **kwargs)\n  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/geopysparkdatacube.py", line 784, in tile_function\n    result_data = run_udf_code(code=udf_code, data=data)\n  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/udf.py", line 36, in run_udf_code\n    return openeo.udf.run_udf_code(code=code, data=data)\n  File "/opt/openeo/lib/python3.8/site-packages/openeo/udf/run_code.py", line 195, in run_udf_code\n    result_cube: xarray.DataArray = func(cube=data.get_datacube_list()[0].get_array(), context=data.user_context)\n  File "<string>", line 173, in apply_datacube\n  File "<string>", line 145, in apply_model\n  File "<string>", line 89, in load_onnx_model\n  File "onnx_dependencies/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__\n    self._create_inference_session(providers, provider_options, disabled_optimizers)\n  File "onnx_dependencies/onnxruntime/capi/onnxruntime_inference_collection.py", line 463, in _create_inference_session\n    sess.initialize_session(providers, provider_options, disabled_optimizers)\nonnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: std::bad_alloc\n\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:561)\n\tat org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:767)\n\tat org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:749)\n\tat org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:514)\n\tat org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)\n\tat scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)\n\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)\n\tat org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)\n\tat org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)\n\tat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:101)\n\tat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)\n\tat org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)\n\tat org.apache.spark.scheduler.Task.run(Task.scala:139)\n\tat org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)\n\tat org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n\nDriver stacktrace:'}, {'id': '[1730638941512, 531146]', 'time': '2024-11-03T13:02:21.512Z', 'level': 'error', 'message': 'OpenEO batch job failed: UDF exception while evaluating processing graph. Please check your user defined functions.   File "/opt/openeo/lib/python3.8/site-packages/openeo/udf/run_code.py", line 195, in run_udf_code\n    result_cube: xarray.DataArray = func(cube=data.get_datacube_list()[0].get_array(), context=data.user_context)\n  File "<string>", line 173, in apply_datacube\n  File "<string>", line 145, in apply_model\n  File "<string>", line 89, in load_onnx_model\n  File "onnx_dependencies/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__\n    self._create_inference_session(providers, provider_options, disabled_optimizers)\n  File "onnx_dependencies/onnxruntime/capi/onnxruntime_inference_collection.py", line 463, in _create_inference_session\n    sess.initialize_session(providers, provider_options, disabled_optimizers)\nonnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: std::bad_alloc'}]

**Comment by HansVRP** [comment]
forgot to add job memory options to the benchmark
