### ISSUE TITLE
As a user, I want to be able to map the credit cost of my algorithm and share it with contributors

### ISSUE THREAD

**Issue by JeroenVerstraelen** [ESA-APEx/apex_algorithms#8]
Creates a graph of the cost by automatically changing spatial and/or temporal extent. 
Automatically stop batch job if it takes too long.

**Comment by HansVRP** [comment]
What I currently envision is:

varying over the spatial extent and temporal extent for a given process graph. 
Then based on the job options we can create performance maps per process graph: 

I already did a small test for ndvi:

![image](https://github.com/ESA-APEx/apex_algorithms/assets/57984106/b7863b69-d174-4c60-a40f-e1b10f3504f3)

Next step is to run the various scenarios through the MultiBackendJobManager

**Comment by HansVRP** [comment]
@jdries 

I do propose to standardize the input parameters for APEX UDPs

Assuming that he spatial extent is always defined through a Parameter.bounding_box(), and the temporal extent through Parameter.temporal_interval will simplify the implementation for automatic cost profiling.

**Comment by HansVRP** [comment]
@jdries what are the potential input parameters for the UDPS and what should we consider for a generally applicable cost profiler?

**Comment by jdries** [comment]
Input parameters now would be spatial and temporal extent. We will try standardizing names, but it's also an option to parse the schema to detect certain types of inputs.
Another typical parameter is an array of enums, like bands. There we could parse the schema, and run tests with e.g. 1 band, 4 bands, all bands, ...

Then another idea is a formula that proposes a cost per square  kilometer, based on the Q90 percentile of cost per area.
For processes where time range contributes heavily to cost, we could do something like cost per km² per month.

I would consider this post-SRR work.
